services:
    kof-bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: kof-bot:latest
        container_name: kof-bot
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./dist:/usr/bot/dist
        restart: unless-stopped
